### ISSUE TITLE
Alta de Cuentas

### ISSUE THREAD

**Issue by Ladito** [ProyectoIntegrador2018/salud360#1]
Como administrador puedo dar de alta cuentas nuevas, ya sea de pacientes, administradores o nutriólogos y asignarles contraseña para poder tener más usuarios en nuestra plataforma.

Puntos de complejidad: 5

Tareas:
- [x] Creación de la base de datos
- [x] Migración de la base de datos
- [x] Creación del formulario para registrar usuario

Criterios de Aceptación:
- [x] Existe el usuario creado en la base de datos.

Definition of Done:
- [x] Funciona correctamente en el servidor.
- [x] Pasar pruebas del documento de pruebas.
- [x] Cada tarea aprobada por un miembro del equipo que no trabajo en la tarea.

**Comment by achavez95** [comment]
Recuerden que los usuarios tienen como username su mail
