### ISSUE TITLE
Inicio de Sesión

### ISSUE THREAD

**Issue by Ladito** [ProyectoIntegrador2018/salud360#2]
Como usuario tengo la capacidad de hacer log in para ver mi información específica.

Puntos de complejidad: 8

Tareas:
- [x] Creación del formulario para iniciar sesión
- [x] Acceso a la base de datos.

Criterios de Aceptación:
- [x] Se logró hacer login con sólo usuarios existentes con la contraseña correcta.

Definition of Done:
- [x] Funciona correctamente en el servidor.
- [x] Pasar pruebas del documento de pruebas.
- [x] Cada tarea aprobada por un miembro del equipo que no trabajo en la tarea.

**Comment by achavez95** [comment]
Aclarando que existen tres tipos de usuario: Administrador, Paciente y Nutriólogo
