### ISSUE TITLE
Error in sessions

### ISSUE THREAD

**Issue by jvann** [ProyectoIntegrador2018/salud360#72]
### Sessions Bug
* The session number does not show the correct session, it says it is 1 and it is actually 2.

Chores:
- [x] Create card in product backlog

Criteria of acceptance:
- [x] All completed tasks
- [x] Shows the correct session and its session number correctly

Definition of Done:
- [x] PR linked with issue closed
- [x] Works correctly in staging.
- [x] Pass tests of the test document.
- [x] Each task approved by a team member who does not work on the task.
- [x] Design is approved by the product owner

**Comment by Rafa4mendoza** [comment]
El conteo de las sesiones debe ser a cuantas lleva el paciente no del listado de las sesiones agendadas.
![image](https://user-images.githubusercontent.com/21150341/55114096-a97f5b80-50a6-11e9-8867-615e563b6a5c.png)

**Comment by jvann** [comment]
Como se sabe cual sesion es si nunca agendo otra ? Es decir como crece el numero de sesiones o como se registra en el sistema la session si no se creo? O cual es el flujo de este contexto?

**Comment by Rafa4mendoza** [comment]
No esta desarrollada una forma de saber que número de sesion es la mayoría de las formas es por un contador:
![image](https://user-images.githubusercontent.com/21150341/55124652-9bdccc80-50cc-11e9-81e9-926b86600f2a.png)
La manera sería un metodo que realize esa función de contador coparando las sesiones por la del metodo current_paciente_next_sessions.
Es posible solo contar las sesiones del paciente pero quedan en esta irregularidad:
![image](https://user-images.githubusercontent.com/21150341/55125200-95e7eb00-50ce-11e9-824a-5c1b38ce519d.png)
