### ISSUE TITLE
Delete button to edit data in nutriologist sessions

### ISSUE THREAD

**Issue by VictorElizalde** [ProyectoIntegrador2018/salud360#89]
### Topic

Chores:
- [x] Create card in product backlog

Criteria of acceptance:
- [x] All completed tasks

Definition of Done:
- [x] PR linked with issue closed
- [x] Works correctly in staging.
- [x] Pass tests of the test document.
- [x] Each task approved by a team member who does not work on the task.
- [x] Design is approved by the product owner

**Comment by Rafa4mendoza** [comment]
Se comentó el botón editar datos para no afectar en futuros desarrollos
![image](https://user-images.githubusercontent.com/21150341/54711550-cf898680-4b0f-11e9-9fc2-af5660c71170.png)
![image](https://user-images.githubusercontent.com/21150341/54711609-e8923780-4b0f-11e9-901d-d4cc89f3089f.png)
