### ISSUE TITLE
Remove point to see diet

### ISSUE THREAD

**Issue by VictorElizalde** [ProyectoIntegrador2018/salud360#90]
### Topic

Chores:
- [x] Create card in product backlog

Criteria of acceptance:
- [x] All completed tasks

Definition of Done:
- [x] PR linked with issue closed
- [x] Works correctly in staging.
- [x] Pass tests of the test document.
- [x] Each task approved by a team member who does not work on the task.
- [x] Design is approved by the product owner

**Comment by Rafa4mendoza** [comment]
Punto eliminado al cambiar la etiqueta de lista
![image](https://user-images.githubusercontent.com/21150341/54710056-8257e580-4b0c-11e9-8cbd-26144345e48d.png)
